### ISSUE TITLE
Issue in MacOS

### ISSUE THREAD

**Issue by santaklouse** [bridgedxyz/ui-labeller#1]
Hi, i have issue with `yarn run dev`

```
$ yarn run dev
yarn run v1.21.1
$ webpack --watch
Failed to load ./.env.

webpack is watching the files…

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[webpack-cli] Uncaught exception: Error: error:0308010C:digital envelope routines::unsupported
[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/ts-loader/dist/index.js:90:5)
    at successLoader (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/ts-loader/dist/index.js:22:12)
    at LOADER_EXECUTION (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/alexnevpryaga/projects/fignel/grida/ui-labeller/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
✨  Done in 1.60s.
```

**Comment by santaklouse** [comment]
I found how to fix it, need to call command below before `yarn run dev`

```
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by MinseokKim-KR** [comment]
Hi @santaklouse  .
Thank you for your information. 
After that command, it doesn't seem to work in my case. 
(Window 11, npm 10.9.0, yarn 1.22.22)

```
$ webpack --watch
Failed to load ./.env.

webpack is watching the files…

Hash: e186806cd7529a241f4f
Version: webpack 4.44.2
Time: 1481ms
Built at: 2025. 01. 05. 오후 12:00:54
    Asset      Size  Chunks             Chunk Names
code.d.ts  74 bytes          [emitted]
  code.js  11.5 KiB    code  [emitted]  code
  ui.d.ts  20 bytes          [emitted]
  ui.html  2.41 MiB          [emitted]
    ui.js  2.41 MiB      ui  [emitted]  ui
Entrypoint ui = ui.js
Entrypoint code = code.js
[../node_modules/css-loader/dist/cjs.js!./src/ui.css] 1.05 KiB {ui} [built]
[./src/code.ts] 1.34 KiB {code} [built]
[./src/ui.css] 1.06 KiB {ui} [built]
[./src/ui.tsx] 1.22 KiB {ui} [built]
    + 14 hidden modules
Child html-webpack-plugin for "ui.html":
     1 asset
    Entrypoint undefined = ui.html
    [../node_modules/html-webpack-plugin/lib/loader.js!./src/ui.html] 224 bytes {0} [built]
        + 3 hidden modules 
```

So I run figma app and import manafest.json, but ```Missing editorType in manifest.  Specify a combination of ["figma", "figjam", "dev"]``` error appeared.

![error_capture](https://github.com/user-attachments/assets/370cce02-7d6b-4458-b6c1-a435ed57453c)

What should I do next? 
Thanks.
